spring:
  datasource:
    url: ${ACCOUNT_DB_URL}
    username: ${ACCOUNT_DB_USERNAME}
    password: ${ACCOUNT_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: ${ACCOUNT_EMAIL_HOST}
    username: ${ACCOUNT_EMAIL_USERNAME}
    password: ${ACCOUNT_EMAIL_PASSWORD}
    port: ${ACCOUNT_EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true      

bolaodacopa:
  app:
    jwtExpirationMs: ${ACCOUNT_TOKEN_EXPIRATIONMS}
  path:
    privateKey: ${ACCOUNT_PATH_PRIVATEKEY}
    publicKey: ${ACCOUNT_PATH_PUBLICKEY}

server:
  port: ${ACCOUNT_DB_PORT}
  error:
    include-message: always